[tool.commitizen]
gpg_sign = true
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
ignored_tag_formats = ["*.post*"]
version = "8.3.2.post1"
update_changelog_on_bump = true
version_files = [
  "setup.cfg:version",
  "stubs/pyproject.toml:version"
]
